name: Static Analysis

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    name: Static Analysis

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04]
        elixir: [1.11.x]
        otp: [23.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Dialyzer PLT cache
        uses: actions/cache@v2
        id: plt-cache
        with:
          path: priv/plts
          key: plt-${{runner.os}}-${{matrix.elixir}}-${{matrix.otp}}-${{hashFiles('lib/**/*.ex')}}
          restore-keys: |
            plt-${{runner.os}}-${{matrix.elixir}}-${{matrix.otp}}-

      - name: Install dependencies
        run: mix do deps.get, deps.compile

      - name: Create Dialyzer PLTs
        if: steps.plt-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p priv/plts
          mix dialyzer --plt

      - name: Run Dialyzer
        run: mix dialyzer
